[phases.setup]
nixPkgs = ["nodejs_18"]

[phases.install]
cmds = [
  "npm install --prefix client --no-audit --no-fund"
]

[phases.build]
cmds = [
  "npm run build --prefix client"
]

[phases.start]
cmd = "gunicorn api.app:app --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 300"


